package org.samuel.Validador;

public enum Carreras {
    INGENIERIADESISTEMAS,
    INGENIERIACIVIL,
    INGENIERIAELECTRICA,
    LICENCIATURAENESCRITURA,
    LICENCIATURAENEDUCACION,
    LICENCIATURAENMATEMATICAS,
    PSICOLOGIA,
    ARQUITECTURA,
    ADMINISTRACION,
    CONTADURIA,
    PERIODISMO,
    DERECHO,
    MEDICINA,
}
